version: "2"
services:
  frontend:
    container_name: front-end
    image: 
    build:
      context: .
      dockerfile: frontend/dockerfile
    ports:
      - "4200:4200"
  backend:
    container_name: php-apache
    image: php:8.0-apache
    dockerfile: backend/dockerfile
    ports:
      - 8000:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - "30002:80"